version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: lazylibrarian_web_1
      APP_PORT: 5299
      PROXY_AUTH_ADD: 'false'
    container_name: lazylibrarian_app_proxy_1
    image: lscr.io/linuxserver/lazylibrarian:latest
    user: '1000:1000'
    restart: on-failure
    environment:
      - CONFIG_PATH=/home/node/config
      - LAZYLIBRARIAN_UID=1000
      - LAZYLIBRARIAN_GID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/home/node/config
      - ${APP_DATA_DIR}/data/metadata:/home/node/metadata
      - ${UMBREL_ROOT}Downloads/plex/downloads:/downloads
    container_name: lazylibrarian_web_1
