---
services:
  lazylibrarian:
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
     - ${APP_DATA_DIR}/data:/config
    - ${UMBREL_ROOT}/home/downloads/plex:/downloads
    ports:
      - 5299:5299
    restart: unless-stopped
