version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: lazylibrarian_web_1
      APP_PORT: 5299
      PROXY_AUTH_ADD: "false"

  web:
    image: lscr.io/linuxserver/lazylibrarian:latest
    user: 1000:1000
    restart: on-failure
    environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
        - ACTUAL_PORT=5299
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${UMBREL_ROOT}Downloads/plex/downloads:/downloads
